nba_city_abb <- data.frame( team = c("Atlanta",
                  "Boston",
                  "Brooklyn",
                  "Charlotte",
                  "Chicago", 
                  "Cleveland",
                  "Dallas",
                  "Denver",
                  "Detroit",
                  "Golden State",
                  "Houston",
                  "Indiana",
                  "LA Clippers",
                  "LA Lakers",
                  "Memphis",
                  "Miami",
                  "Milwaukee",
                  "Minnesota",
                  "New Jersey",
                  "New Orleans",
                  "New Orleans/Oklahoma City",
                  "New York",
                  "Oklahoma City",
                  "Orlando",
                  "Philadelphia",
                  "Phoenix",
                  "Portland",
                  "Sacramento",
                  "San Antonio",
                  "Seattle",
                  "Toronto",
                  "Utah",
                  "Washington"),
                  abb =  c("ATL",
                           "BOS",
                           "BRK",
                           "CHA",
                           "CHI",
                           "CLE",
                           "DAL",
                           "DEN",
                           "DET",
                           "GSW",
                           "HOU",
                           "IND",
                           "LAC",
                           "LAL",
                           "MEM",
                           "MIA",
                           "MIL",
                           "MIN",
                           "NJN",
                           "NOP",
                           "NOP",
                           "NYK",
                           "OKC",
                           "ORL",
                           "PHI",
                           "PHO",
                           "POR",
                           "SAC",
                           "SAS",
                           "SEA",
                           "TOR",
                           "UTA",
                           "WAS"))
                           
